### PR TITLE
Add Swarm link to annotations

### PR DESCRIPTION
**Pull request by howardcvalve**
* Adds a config option `swarmHost` to specify as the hostname to link to
* If configured, allows clicking on a annotation hover to go to that change in Swarm.

### CODE REVIEW

**Comment by stef-levesque** [comment]
This is quite useful, thanks !

A few comments:
- Should we add the protocol to the swarm host ? (http://...)
- Maybe add the link on its own line and text ? (Open Changelist in Swarm)

I can also accept the PR as-is and look at it later on.

**Comment by howardcvalve** [comment]
Added the protocol to the config value.

I think it's fine to leave the link as-is and have been using it for a while that way, but can adjust in response to user feedback.

**Comment by howardcvalve** [comment]
Hi,

Do you have a timeframe for when the next release will ship?

**Comment by samtsai** [comment]
Bump, I still do not see this option available.  Can we get a new release?

**Comment by howardcvalve** [comment]
Hi @stef-levesque, would you be able to publish a new release with this feature?

**Comment by samtsai** [comment]
@stef-levesque any chance we could get this released?

**Comment by mjcrouch** [comment]
HI @samtsai 

This was in master before I made [my fork](https://marketplace.visualstudio.com/items?itemName=mjcrouch.perforce) - so it's in the published version if you want to try it.

(I just tried it and did notice a minor issue that if you don't have `perforce.annotate.user` enabled, all the swarm links have the text "undefined" in them)

(don't forget to disable slevesque.perforce before using it or everything goes crazy)

**Comment by samtsai** [comment]
So I'm able to see the links now!  Unfortunately the link points to: https://SWARM_HOST/changes/NUM

I'm not sure my company's Swarm is setup that way, I'd ideally want to point to the specific file and change number.

**Comment by mjcrouch** [comment]
I've never used swarm so I'm not sure how the links work but it purports to be free so I may see if I can do something about it when I get a chance

**Comment by mjcrouch** [comment]
Also it occured to me the default annotation view shows revisions instead of changelist numbers, but there's a setting to change it, which will affect the link it generates

Don't know if that makes a difference for your swarm setup, but definitely this change needs some more work as it's only compatible with certain settings

**Pull request merged**
