### PR TITLE
Throttle all perforce commands via bottleneck

### PR DESCRIPTION
**Pull request by pjdanfor**
Throttle all perforce commands via bottleneck

### CODE REVIEW

**Comment by stef-levesque** [comment]
Thanks, this looks great !
I think we should make the `highWater` configurable. I can have a look.

**Comment by pjdanfor** [comment]
Thanks a lot for merging this! Totally agree - I obviously didn't put a ton of time into testing this or making it very configurable. Could look at the `bottleneck` configuration options and see what makes sense to make configurable via your plugin. I am about to setup jest and write some tests. I also think there is likely more work to be done as far as ensuring the dropped perforce command is indeed halted and not just executing in the nether somewhere. There is an "on dropped" callback that can be made use of via the `bottleneck` module which I think is likely necessary. Probably will have to keep track of the child processes generated via the perforce commands and end them whenever they are dropped from the queue.

**Comment by stef-levesque** [comment]
I tried to expose the best I could in 7c5339f7f40c7c0154d82018789853c3935e9489

I also updated the pre-release build available here: https://github.com/stef-levesque/vscode-perforce/releases

You can download and install the `.vsix` file via the VSCode command palette:
`Extensions: Install from VSIX...`

**Comment by pjdanfor** [comment]
Looks great! Okay, sounds good. Thanks so much.

**Pull request merged**
